/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  name?: string;
  email?: string;
  orders?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "order";
  }>;
  totalSpent?: number;
  createdAt?: string;
};

export type Sale = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    customizations?: {
      dimensions?: string;
      material?: string;
      roofType?: string;
      doors?: number;
      windows?: number;
      garage?: boolean;
      addons?: Array<string>;
    };
    price?: number;
    quantity?: number;
    _key: string;
  }>;
  totalPrice?: number;
  tax?: number;
  currency?: string;
  amountDiscount?: number;
  orderType?: "reservation";
  paymentStatus?: "unpaid" | "paid_in_store" | "paid_online";
  pickupStatus?: "pending" | "completed";
  orderDate?: string;
  paymentMethod?: "online_unpaid" | "cash" | "card" | "split";
  cashReceived?: number;
  cardAmount?: number;
  changeGiven?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  itemNumber?: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  extraImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  baseVariants?: Array<{
    dimensions?: string;
    basePrice?: number;
    _type: "baseVariant";
    _key: string;
  }>;
  materials?: Array<{
    name?: string;
    price?: number;
    _type: "materialOption";
    _key: string;
  }>;
  roofTypes?: Array<{
    name?: string;
    price?: number;
    _type: "roofOption";
    _key: string;
  }>;
  addons?: Array<{
    name?: string;
    price?: number;
    _type: "addonOption";
    _key: string;
  }>;
  garagePrice?: number;
  doorPrice?: number;
  windowPrice?: number;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Customer | Sale | Order | Product | Category | BlockContent | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/app/api/admin/orders/get-order/route.ts
// Variable: query
// Query: *[_type == "order" && orderNumber == $orderNumber][0]{        _id,        orderNumber,        clerkUserId,        customerName,        email,        products[] {          _key,          quantity,          itemNumber,          price,          variant,          product->{            _id,            name,            slug,            image,            itemNumber,            stock,            category->{              title            },            variants[] {              _key,              name,              price,              stock            }          }        },        totalPrice,        tax,        currency,        amountDiscount,        orderType,        paymentStatus,        pickupStatus,        orderDate,        paymentMethod,        cashReceived,        cardAmount,        changeGiven      }
export type QueryResult = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  customerName: string | null;
  email: string | null;
  products: Array<{
    _key: string;
    quantity: number | null;
    itemNumber: null;
    price: number | null;
    variant: null;
    product: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      itemNumber: string | null;
      stock: null;
      category: {
        title: string | null;
      } | null;
      variants: null;
    } | null;
  }> | null;
  totalPrice: number | null;
  tax: number | null;
  currency: string | null;
  amountDiscount: number | null;
  orderType: "reservation" | null;
  paymentStatus: "paid_in_store" | "paid_online" | "unpaid" | null;
  pickupStatus: "completed" | "pending" | null;
  orderDate: string | null;
  paymentMethod: "card" | "cash" | "online_unpaid" | "split" | null;
  cashReceived: number | null;
  cardAmount: number | null;
  changeGiven: number | null;
} | null;

// Source: ./src/sanity/lib/orders/getMyOrders.tsx
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc) {        ...,        products[]{            ...,            product->        }    }
export type MY_ORDERS_QUERYResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      itemNumber?: string;
      name?: string;
      slug?: Slug;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
      extraImages?: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      description?: string;
      baseVariants?: Array<{
        dimensions?: string;
        basePrice?: number;
        _type: "baseVariant";
        _key: string;
      }>;
      materials?: Array<{
        name?: string;
        price?: number;
        _type: "materialOption";
        _key: string;
      }>;
      roofTypes?: Array<{
        name?: string;
        price?: number;
        _type: "roofOption";
        _key: string;
      }>;
      addons?: Array<{
        name?: string;
        price?: number;
        _type: "addonOption";
        _key: string;
      }>;
      garagePrice?: number;
      doorPrice?: number;
      windowPrice?: number;
      category?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "category";
      };
    } | null;
    customizations?: {
      dimensions?: string;
      material?: string;
      roofType?: string;
      doors?: number;
      windows?: number;
      garage?: boolean;
      addons?: Array<string>;
    };
    price?: number;
    quantity?: number;
    _key: string;
  }> | null;
  totalPrice?: number;
  tax?: number;
  currency?: string;
  amountDiscount?: number;
  orderType?: "reservation";
  paymentStatus?: "paid_in_store" | "paid_online" | "unpaid";
  pickupStatus?: "completed" | "pending";
  orderDate?: string;
  paymentMethod?: "card" | "cash" | "online_unpaid" | "split";
  cashReceived?: number;
  cardAmount?: number;
  changeGiven?: number;
}>;

// Source: ./src/sanity/lib/products/getAllCategories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == 'category'] | order(title asc) {    _id,    _type,    _createdAt,    _updatedAt,    _rev,    title,    slug,    description,    image  }
export type ALL_CATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ./src/sanity/lib/products/getProductsByCategory.tsx
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[_type == 'product' && references(*[_type == 'category' && slug.current == $categorySlug]._id)] | order(name asc) {      _id,      _type,      _createdAt,      _updatedAt,      _rev,      itemNumber,      name,      slug,      price,      stock,      description,      // 🖼️ Resolve main image to URL      image,      "imageUrl": image.asset->url,      // 🖼️ Resolve extra images to URLs      extraImages,      "extraImageUrls": extraImages[].asset->url,      // 📦 Variants      variants[] {        size,        dimensions,        material,        roof,        price,        stock,        windows,        doors,        garage,        addons      },      // 🏷️ Resolved Category      category->{        _id,        title,        slug,        description,        image,        "imageUrl": image.asset->url      }    }
export type PRODUCTS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  itemNumber: string | null;
  name: string | null;
  slug: Slug | null;
  price: null;
  stock: null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageUrl: string | null;
  extraImages: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  extraImageUrls: Array<string | null> | null;
  variants: null;
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    imageUrl: string | null;
  } | null;
}>;

// Source: ./src/sanity/lib/sales/getActiveSaleByCouponCode.ts
// Variable: ACTIVE_SALE_BY_COUPON_QUERY
// Query: *[        _type == 'sale'        && isActive == true         && couponCode == $couponCode    ] | order(validFfrom desc)[0]
export type ACTIVE_SALE_BY_COUPON_QUERYResult = {
  _id: string;
  _type: "sale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  discountAmount?: number;
  couponCode?: string;
  validFrom?: string;
  validUntil?: string;
  isActive?: boolean;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n      *[_type == \"order\" && orderNumber == $orderNumber][0]{\n        _id,\n        orderNumber,\n        clerkUserId,\n        customerName,\n        email,\n        products[] {\n          _key,\n          quantity,\n          itemNumber,\n          price,\n          variant,\n          product->{\n            _id,\n            name,\n            slug,\n            image,\n            itemNumber,\n            stock,\n            category->{\n              title\n            },\n            variants[] {\n              _key,\n              name,\n              price,\n              stock\n            }\n          }\n        },\n        totalPrice,\n        tax,\n        currency,\n        amountDiscount,\n        orderType,\n        paymentStatus,\n        pickupStatus,\n        orderDate,\n        paymentMethod,\n        cashReceived,\n        cardAmount,\n        changeGiven\n      }\n    ": QueryResult;
    "\n    *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc) {\n        ...,\n        products[]{\n            ...,\n            product->\n        }\n    }\n  ": MY_ORDERS_QUERYResult;
    "\n  *[_type == 'category'] | order(title asc) {\n    _id,\n    _type,\n    _createdAt,\n    _updatedAt,\n    _rev,\n    title,\n    slug,\n    description,\n    image\n  }\n": ALL_CATEGORIES_QUERYResult;
    "\n    *[_type == 'product' && references(*[_type == 'category' && slug.current == $categorySlug]._id)] | order(name asc) {\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      itemNumber,\n      name,\n      slug,\n      price,\n      stock,\n      description,\n\n      // \uD83D\uDDBC\uFE0F Resolve main image to URL\n      image,\n      \"imageUrl\": image.asset->url,\n\n      // \uD83D\uDDBC\uFE0F Resolve extra images to URLs\n      extraImages,\n      \"extraImageUrls\": extraImages[].asset->url,\n\n      // \uD83D\uDCE6 Variants\n      variants[] {\n        size,\n        dimensions,\n        material,\n        roof,\n        price,\n        stock,\n        windows,\n        doors,\n        garage,\n        addons\n      },\n\n      // \uD83C\uDFF7\uFE0F Resolved Category\n      category->{\n        _id,\n        title,\n        slug,\n        description,\n        image,\n        \"imageUrl\": image.asset->url\n      }\n    }\n  ": PRODUCTS_BY_CATEGORY_QUERYResult;
    "\n    *[\n        _type == 'sale'\n        && isActive == true \n        && couponCode == $couponCode\n    ] | order(validFfrom desc)[0]\n    ": ACTIVE_SALE_BY_COUPON_QUERYResult;
  }
}
